export interface IndonesianMobileBankInfo {
  id: string;
  appName: string;
  affiliatedBank: string;
  shortCode: string;
  tagline: string;
  brandColor: string;
  textColor: string;
  keywords: string[];
  senderDomains: string[];
  accountTypeDefault: 'checking' | 'savings' | 'credit' | 'digital_wallet';
  iconType: 'Building2' | 'Smartphone' | 'CreditCard' | 'Wallet';
}

export const INDONESIAN_MOBILE_BANKS: IndonesianMobileBankInfo[] = [
  {
    id: 'bni_wondr',
    appName: 'wondr by BNI',
    affiliatedBank: 'Bank Negara Indonesia (BNI)',
    shortCode: 'BNI',
    tagline: 'Transaksi, Insight, & Growth',
    brandColor: '#005E54',
    textColor: '#FFFFFF',
    keywords: [
      'wondr',
      'wonder',
      'wondr by bni',
      'bni mobile',
      'bni direct',
      'taplus bni',
      'bni qris',
      'bank bni',
    ],
    senderDomains: ['bni.co.id', 'wondr@bni.co.id', 'bnicall@bni.co.id'],
    accountTypeDefault: 'checking',
    iconType: 'Smartphone',
  },
  {
    id: 'bca_mybca',
    appName: 'myBCA',
    affiliatedBank: 'Bank Central Asia (BCA)',
    shortCode: 'BCA',
    tagline: 'Single identity digital banking BCA',
    brandColor: '#005EB8',
    textColor: '#FFFFFF',
    keywords: [
      'mybca',
      'my bca',
      'bca id',
      'klikbca',
      'bca mobile',
      'm-bca',
      'qris bca',
      'paspor bca',
      'tahapan bca',
    ],
    senderDomains: ['bca.co.id', 'klikbca.com', 'ebanking@bca.co.id'],
    accountTypeDefault: 'checking',
    iconType: 'Smartphone',
  },
  {
    id: 'bca_mobile',
    appName: 'BCA mobile',
    affiliatedBank: 'Bank Central Asia (BCA)',
    shortCode: 'BCA',
    tagline: 'm-BCA & KlikBCA Individual',
    brandColor: '#003399',
    textColor: '#FFFFFF',
    keywords: ['bca mobile', 'm-bca', 'mbca', 'bca debit', 'rekening tahapan'],
    senderDomains: ['bca.co.id', 'klikbca.com'],
    accountTypeDefault: 'checking',
    iconType: 'Building2',
  },
  {
    id: 'bca_digital_blu',
    appName: 'blu by BCA Digital',
    affiliatedBank: 'blu by BCA Digital (BCA Group)',
    shortCode: 'blu',
    tagline: 'Next-gen digital banking by BCA Digital',
    brandColor: '#00B4D8',
    textColor: '#001A3D',
    keywords: [
      'blu',
      'blubybcadigital',
      'blu by bca',
      'bcadigital',
      'haloblu',
      'bluaccount',
      'bludebit',
    ],
    senderDomains: ['bcadigital.co.id', 'haloblu@bcadigital.co.id'],
    accountTypeDefault: 'checking',
    iconType: 'Smartphone',
  },
  {
    id: 'mandiri_livin',
    appName: "Livin' by Mandiri",
    affiliatedBank: 'Bank Mandiri',
    shortCode: 'Mandiri',
    tagline: 'Financial Super App beyond banking',
    brandColor: '#003D79',
    textColor: '#FFCC00',
    keywords: [
      'livin',
      "livin'",
      "livin' by mandiri",
      'livin by mandiri',
      'mandiri online',
      'mandiri now',
      'kopra',
      'mandiri qris',
      'sukha',
    ],
    senderDomains: ['bankmandiri.co.id', 'mandiricare@bankmandiri.co.id'],
    accountTypeDefault: 'checking',
    iconType: 'Smartphone',
  },
  {
    id: 'bri_brimo',
    appName: 'BRImo',
    affiliatedBank: 'Bank Rakyat Indonesia (BRI)',
    shortCode: 'BRI',
    tagline: 'Financial Super App perbankan BRI',
    brandColor: '#00529C',
    textColor: '#FFFFFF',
    keywords: [
      'brimo',
      'bri mobile',
      'britama',
      'simpedes',
      'ceria bri',
      'bri qris',
      'bank bri',
      'bri debit',
    ],
    senderDomains: ['bri.co.id', 'brimo@bri.co.id', 'contactbri@bri.co.id'],
    accountTypeDefault: 'checking',
    iconType: 'Smartphone',
  },
  {
    id: 'bsi_byond',
    appName: 'BYOND by BSI',
    affiliatedBank: 'Bank Syariah Indonesia (BSI)',
    shortCode: 'BSI',
    tagline: 'Sahabat Finansial, Sosial & Spiritual',
    brandColor: '#00A39D',
    textColor: '#FFFFFF',
    keywords: [
      'byond',
      'byond by bsi',
      'bsi byond',
      'bsi mobile',
      'bank bsi',
      'hasanah debit',
      'bsi net',
      'tabungan wadiah',
    ],
    senderDomains: [
      'bankbsi.co.id',
      'contactus@bankbsi.co.id',
      'byond@bankbsi.co.id',
    ],
    accountTypeDefault: 'checking',
    iconType: 'Smartphone',
  },
  {
    id: 'btn_bale',
    appName: 'balé by BTN',
    affiliatedBank: 'Bank Tabungan Negara (BTN)',
    shortCode: 'BTN',
    tagline: 'Ekosistem perumahan & transaksi digital BTN',
    brandColor: '#F58220',
    textColor: '#FFFFFF',
    keywords: [
      'bale',
      'balé',
      'bale by btn',
      'balé by btn',
      'btn mobile',
      'bank btn',
      'btn properti',
      'tabungan batara',
    ],
    senderDomains: [
      'btn.co.id',
      'btncontactcenter@btn.co.id',
      'bale@btn.co.id',
    ],
    accountTypeDefault: 'checking',
    iconType: 'Smartphone',
  },
  {
    id: 'btpn_jenius',
    appName: 'Jenius (Bank BTPN)',
    affiliatedBank: 'Bank BTPN (Jenius)',
    shortCode: 'Jenius',
    tagline: 'Pioneer life finance digital banking',
    brandColor: '#00A3E0',
    textColor: '#FFFFFF',
    keywords: [
      'jenius',
      'jenius btpn',
      'btpn',
      'cashtag',
      'm-card',
      'e-card',
      'x-card',
      'flexi saver',
      'maxi saver',
      'jenius pay',
    ],
    senderDomains: ['btpn.com', 'jenius.com', 'jenius-help@btpn.com'],
    accountTypeDefault: 'checking',
    iconType: 'Smartphone',
  },
  {
    id: 'cimb_octo',
    appName: 'OCTO Mobile',
    affiliatedBank: 'Bank CIMB Niaga',
    shortCode: 'CIMB',
    tagline: 'Super App perbankan CIMB Niaga',
    brandColor: '#7A0026',
    textColor: '#FFFFFF',
    keywords: [
      'octo',
      'octo mobile',
      'octo clicks',
      'octo pay',
      'octo savers',
      'cimb niaga',
      'cimb',
      'rekening ponsel',
    ],
    senderDomains: [
      'cimbniaga.co.id',
      '14041@cimbniaga.co.id',
      'octomobile@cimbniaga.co.id',
    ],
    accountTypeDefault: 'checking',
    iconType: 'Smartphone',
  },
  {
    id: 'jago_app',
    appName: 'Bank Jago',
    affiliatedBank: 'Bank Jago',
    shortCode: 'Jago',
    tagline: 'Kantong pintar pengelolaan finansial',
    brandColor: '#8B5CF6',
    textColor: '#FFFFFF',
    keywords: [
      'jago',
      'bank jago',
      'jago syariah',
      'kantong jago',
      'jago pocket',
      'jago visa debit',
      'jago x gopay',
    ],
    senderDomains: ['jago.com', 'tanya@jago.com'],
    accountTypeDefault: 'checking',
    iconType: 'Smartphone',
  },
  {
    id: 'permata_me',
    appName: 'PermataME / PermataMobile X',
    affiliatedBank: 'PermataBank',
    shortCode: 'Permata',
    tagline: 'Digital banking mobile PermataBank',
    brandColor: '#00875A',
    textColor: '#FFFFFF',
    keywords: [
      'permatame',
      'permata me',
      'permatamobile',
      'permatamobile x',
      'permatabank',
      'permata net',
      'permata qris',
    ],
    senderDomains: ['permatabank.co.id', 'care@permatabank.co.id'],
    accountTypeDefault: 'checking',
    iconType: 'Smartphone',
  },
  {
    id: 'danamon_dbank',
    appName: 'D-Bank PRO',
    affiliatedBank: 'Bank Danamon',
    shortCode: 'Danamon',
    tagline: 'Mobile banking Danamon serba bisa',
    brandColor: '#FF6600',
    textColor: '#FFFFFF',
    keywords: [
      'd-bank',
      'dbank',
      'dbank pro',
      'd-bank pro',
      'bank danamon',
      'danamon online',
    ],
    senderDomains: ['danamon.co.id', 'hellodanamon@danamon.co.id'],
    accountTypeDefault: 'checking',
    iconType: 'Smartphone',
  },
  {
    id: 'mega_msmile',
    appName: 'M-Smile',
    affiliatedBank: 'Bank Mega',
    shortCode: 'Mega',
    tagline: 'Mega Mobile & Kartu Kredit App',
    brandColor: '#E65100',
    textColor: '#FFFFFF',
    keywords: [
      'm-smile',
      'msmile',
      'mega mobile',
      'bank mega',
      'mega credit card',
    ],
    senderDomains: ['bankmega.com', 'halomega@bankmega.com'],
    accountTypeDefault: 'checking',
    iconType: 'Smartphone',
  },
  {
    id: 'ocbc_mobile',
    appName: 'OCBC mobile',
    affiliatedBank: 'Bank OCBC NISP',
    shortCode: 'OCBC',
    tagline: 'Nyala digital banking OCBC',
    brandColor: '#D90429',
    textColor: '#FFFFFF',
    keywords: [
      'ocbc mobile',
      'one mobile',
      'ocbc nisp',
      'nyala ocbc',
      'ocbc velocity',
    ],
    senderDomains: ['ocbc.id', 'ocbcnisp.com', 'tanya@ocbc.id'],
    accountTypeDefault: 'checking',
    iconType: 'Smartphone',
  },
  {
    id: 'panin_mobile',
    appName: 'Panin Mobile',
    affiliatedBank: 'Bank Panin',
    shortCode: 'Panin',
    tagline: 'Mobile banking Panin Bank',
    brandColor: '#004B87',
    textColor: '#FFFFFF',
    keywords: [
      'panin mobile',
      'panin digital',
      'bank panin',
      'panin internet banking',
    ],
    senderDomains: ['panin.co.id', 'callpanin@panin.co.id'],
    accountTypeDefault: 'checking',
    iconType: 'Building2',
  },
  {
    id: 'seabank_app',
    appName: 'SeaBank',
    affiliatedBank: 'SeaBank Indonesia',
    shortCode: 'SeaBank',
    tagline: 'Digital banking bunga harian by Sea Group',
    brandColor: '#FF5722',
    textColor: '#FFFFFF',
    keywords: [
      'seabank',
      'seabank indonesia',
      'sea bank',
      'seabank transfer',
      'seabank x shopee',
    ],
    senderDomains: ['seabank.co.id', 'cs@seabank.co.id'],
    accountTypeDefault: 'checking',
    iconType: 'Smartphone',
  },
  {
    id: 'allo_bank',
    appName: 'Allo Bank',
    affiliatedBank: 'Allo Bank Indonesia',
    shortCode: 'Allo',
    tagline: 'One app for everything CT Corp ecosystem',
    brandColor: '#1E40AF',
    textColor: '#FFFFFF',
    keywords: ['allo', 'allo bank', 'allo app', 'allo prime', 'allo paylater'],
    senderDomains: ['allobank.com', 'contactus@allobank.com'],
    accountTypeDefault: 'checking',
    iconType: 'Smartphone',
  },
  {
    id: 'superbank_app',
    appName: 'Superbank',
    affiliatedBank: 'Superbank Indonesia',
    shortCode: 'Superbank',
    tagline: 'Bank digital Grab, Singtel & Emtek',
    brandColor: '#0D9488',
    textColor: '#FFFFFF',
    keywords: [
      'superbank',
      'superbank indonesia',
      'superbank x grab',
      'super bank',
    ],
    senderDomains: ['superbank.id', 'care@superbank.id'],
    accountTypeDefault: 'checking',
    iconType: 'Smartphone',
  },
  {
    id: 'bank_raya_app',
    appName: 'Raya by Bank Raya',
    affiliatedBank: 'Bank Raya (BRI Group)',
    shortCode: 'Raya',
    tagline: 'Digital bank by Bank Rakyat Indonesia',
    brandColor: '#0284C7',
    textColor: '#FFFFFF',
    keywords: ['raya', 'bank raya', 'saku raya', 'bank raya indonesia'],
    senderDomains: ['bankraya.co.id', 'ragam@bankraya.co.id'],
    accountTypeDefault: 'checking',
    iconType: 'Smartphone',
  },
  {
    id: 'neobank_bnc',
    appName: 'Neobank',
    affiliatedBank: 'Bank Neo Commerce',
    shortCode: 'BNC',
    tagline: 'Bank Neo Commerce digital banking',
    brandColor: '#FFB800',
    textColor: '#001A3D',
    keywords: [
      'neobank',
      'neo bank',
      'bank neo',
      'bank neo commerce',
      'neo wow',
    ],
    senderDomains: ['bankneo.co.id', 'notifikasi@bankneo.co.id'],
    accountTypeDefault: 'checking',
    iconType: 'Smartphone',
  },
  {
    id: 'line_bank',
    appName: 'LINE Bank by Hana Bank',
    affiliatedBank: 'LINE Bank (Hana Bank)',
    shortCode: 'LINE Bank',
    tagline: 'Digital banking seru & praktis bersama LINE',
    brandColor: '#00C300',
    textColor: '#FFFFFF',
    keywords: ['line bank', 'linebank', 'hana bank', 'keb hana', 'line debit'],
    senderDomains: ['linebank.co.id', 'help@linebank.co.id'],
    accountTypeDefault: 'checking',
    iconType: 'Smartphone',
  },
  {
    id: 'uob_tmrw',
    appName: 'TMRW by UOB',
    affiliatedBank: 'Bank UOB Indonesia (TMRW)',
    shortCode: 'TMRW',
    tagline: 'Digital bank for digital generation by UOB',
    brandColor: '#6B21A8',
    textColor: '#FFFFFF',
    keywords: [
      'tmrw',
      'tmrw by uob',
      'uob tmrw',
      'uob indonesia',
      'uob mighty',
    ],
    senderDomains: ['uob.co.id', 'tmrw@uob.co.id'],
    accountTypeDefault: 'checking',
    iconType: 'Smartphone',
  },
  {
    id: 'dbs_digibank',
    appName: 'digibank by DBS',
    affiliatedBank: 'Bank DBS Indonesia (digibank)',
    shortCode: 'digibank',
    tagline: 'Live more, Bank less with digibank',
    brandColor: '#E11D48',
    textColor: '#FFFFFF',
    keywords: ['digibank', 'digibank by dbs', 'dbs indonesia', 'dbs bank'],
    senderDomains: ['dbs.com', 'digibankid@dbs.com'],
    accountTypeDefault: 'checking',
    iconType: 'Smartphone',
  },
  {
    id: 'sinarmas_simobi',
    appName: 'SimobiPlus',
    affiliatedBank: 'Bank Sinarmas',
    shortCode: 'Sinarmas',
    tagline: 'Mobile banking Bank Sinarmas',
    brandColor: '#DC2626',
    textColor: '#FFFFFF',
    keywords: ['simobi', 'simobiplus', 'simobi plus', 'bank sinarmas', 'simas'],
    senderDomains: ['banksinarmas.com', 'care@banksinarmas.com'],
    accountTypeDefault: 'checking',
    iconType: 'Smartphone',
  },
  {
    id: 'muamalat_din',
    appName: 'Muamalat DIN',
    affiliatedBank: 'Bank Muamalat Indonesia',
    shortCode: 'Muamalat',
    tagline: 'Digital Islamic Network Muamalat',
    brandColor: '#701A75',
    textColor: '#FFFFFF',
    keywords: [
      'muamalat din',
      'muamalatdin',
      'muamalat mobile',
      'bank muamalat',
    ],
    senderDomains: ['bankmuamalat.co.id', 'salamuamalat@bankmuamalat.co.id'],
    accountTypeDefault: 'checking',
    iconType: 'Smartphone',
  },
  {
    id: 'maybank_m2u',
    appName: 'M2U ID',
    affiliatedBank: 'Bank Maybank Indonesia',
    shortCode: 'Maybank',
    tagline: 'Maybank2u ID digital banking',
    brandColor: '#FACC15',
    textColor: '#001A3D',
    keywords: [
      'm2u',
      'm2u id',
      'maybank2u',
      'maybank indonesia',
      'bank maybank',
    ],
    senderDomains: ['maybank.co.id', 'customercare@maybank.co.id'],
    accountTypeDefault: 'checking',
    iconType: 'Smartphone',
  },
  // Major E-Wallets
  {
    id: 'wallet_gopay',
    appName: 'GoPay / GoPay Tabungan',
    affiliatedBank: 'GoPay Indonesia (GoTo / Bank Jago)',
    shortCode: 'GoPay',
    tagline: 'Dompet digital & Tabungan GoPay',
    brandColor: '#00AA13',
    textColor: '#FFFFFF',
    keywords: [
      'gopay',
      'gojek',
      'goto',
      'gofood',
      'goride',
      'gocar',
      'gopay tabungan',
      'gopay coins',
    ],
    senderDomains: ['go-jek.com', 'gojek.com', 'receipt@go-jek.com'],
    accountTypeDefault: 'digital_wallet',
    iconType: 'Wallet',
  },
  {
    id: 'wallet_ovo',
    appName: 'OVO',
    affiliatedBank: 'OVO (PT Visionet Internasional)',
    shortCode: 'OVO',
    tagline: 'Dompet digital OVO Cash & OVO Points',
    brandColor: '#4C3494',
    textColor: '#FFFFFF',
    keywords: ['ovo', 'ovo cash', 'ovo points', 'ovo id', 'ovo premier'],
    senderDomains: ['ovo.id', 'no-reply@ovo.id'],
    accountTypeDefault: 'digital_wallet',
    iconType: 'Wallet',
  },
  {
    id: 'wallet_dana',
    appName: 'DANA',
    affiliatedBank: 'DANA (PT Espay Debit Indonesia)',
    shortCode: 'DANA',
    tagline: 'Dompet Digital Indonesia DANA',
    brandColor: '#118EEA',
    textColor: '#FFFFFF',
    keywords: [
      'dana',
      'dana saldo',
      'dana indonesia',
      'dana premium',
      'dana qris',
    ],
    senderDomains: ['dana.id', 'notification@dana.id'],
    accountTypeDefault: 'digital_wallet',
    iconType: 'Wallet',
  },
  {
    id: 'wallet_shopeepay',
    appName: 'ShopeePay',
    affiliatedBank: 'ShopeePay & SPayLater',
    shortCode: 'ShopeePay',
    tagline: 'Dompet digital & PayLater Shopee',
    brandColor: '#EE4D2D',
    textColor: '#FFFFFF',
    keywords: [
      'shopeepay',
      'shopee pay',
      'spaylater',
      'shopee',
      'spay later',
      'shopeepay plus',
    ],
    senderDomains: ['shopee.co.id', 'notifikasi@shopee.co.id'],
    accountTypeDefault: 'digital_wallet',
    iconType: 'Wallet',
  },
  {
    id: 'wallet_linkaja',
    appName: 'LinkAja',
    affiliatedBank: 'LinkAja (PT Fintek Karya Nusantara)',
    shortCode: 'LinkAja',
    tagline: 'Dompet digital BUMN LinkAja',
    brandColor: '#ED1C24',
    textColor: '#FFFFFF',
    keywords: ['linkaja', 'link aja', 'linkaja syariah', 'tcash'],
    senderDomains: ['linkaja.id', 'info@linkaja.id'],
    accountTypeDefault: 'digital_wallet',
    iconType: 'Wallet',
  },
  {
    id: 'wallet_astrapay',
    appName: 'AstraPay',
    affiliatedBank: 'AstraPay (Astra Group)',
    shortCode: 'AstraPay',
    tagline: 'Dompet digital ekosistem Astra',
    brandColor: '#002B49',
    textColor: '#FFFFFF',
    keywords: ['astrapay', 'astra pay', 'fifgroup'],
    senderDomains: ['astrapay.com'],
    accountTypeDefault: 'digital_wallet',
    iconType: 'Wallet',
  },
];

/**
 * Resolves any email sender, subject, or body text to an affiliated Indonesian bank / mobile app.
 */
export function resolveIndonesianBankApp(text: string): {
  matched: boolean;
  bankInfo: IndonesianMobileBankInfo | null;
  displayBankName: string;
  displayPaymentMethod: string;
} {
  const lower = (text || '').toLowerCase();

  // Try exact or word boundary matching against all app definitions
  for (const bank of INDONESIAN_MOBILE_BANKS) {
    for (const kw of bank.keywords) {
      // Regex check with boundary or simple word presence
      const regex = new RegExp(
        `\\b${kw.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&')}\\b`,
        'i'
      );
      if (regex.test(lower) || lower.includes(kw)) {
        let paymentMethod = `${bank.appName}`;
        if (/qris/i.test(lower)) {
          paymentMethod = `${bank.shortCode} QRIS (${bank.appName})`;
        } else if (/kartu kredit|credit card/i.test(lower)) {
          paymentMethod = `${bank.shortCode} Credit Card`;
        } else if (/debit|paspor|britama|taplus|tabungan|m-card/i.test(lower)) {
          paymentMethod = `${bank.shortCode} Debit (${bank.appName})`;
        } else if (/transfer|bi-fast|bifast/i.test(lower)) {
          paymentMethod = `${bank.shortCode} BI-FAST (${bank.appName})`;
        }

        return {
          matched: true,
          bankInfo: bank,
          displayBankName: `${bank.affiliatedBank} (${bank.appName})`,
          displayPaymentMethod: paymentMethod,
        };
      }
    }
  }

  return {
    matched: false,
    bankInfo: null,
    displayBankName: 'Bank Transfer / Digital Account',
    displayPaymentMethod: 'Bank Transfer',
  };
}

/**
 * Returns a clean display name combining Bank & Mobile App
 */
export function formatBankWithMobileApp(
  bankName: string,
  appName?: string
): string {
  if (!bankName) return 'Bank Account';
  if (appName && !bankName.toLowerCase().includes(appName.toLowerCase())) {
    return `${bankName} (${appName})`;
  }
  return bankName;
}
